ElectionDataAnalysis/electiondata

- src/mungers/fl_gen_by_county/cdf_elements.txt
- src/mungers/fl_gen_by_county/format.config
- src/mungers/fl_gen_by_precinct/cdf_elements.txt
- src/mungers/fl_gen_by_precinct/format.config
- src/mungers/fl_pri_by_county/cdf_elements.txt
- src/mungers/fl_pri_by_county/format.config
- src/mungers/fl_pri_pres/cdf_elements.txt
- src/mungers/fl_pri_pres/format.config
> Issue11 create mungers

- src/election_data_analysis/__init__.py
> Issue17 error msg

- src/election_data_analysis/CDF_schema_def_info/elements/VoteCount/unique_constraints.txt
> add natural uniqueness constraint for VoteCount

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/database/create_cdf_db/__init__.py
- src/election_data_analysis/preparation/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/election_data_analysis/verify_results/__init__.py
- src/election_data_analysis/visualize/__init__.py
> remove unused import statements

- docs/User_Guide.md
> describe .errors files

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/special_formats/__init__.py
Closes #32 and #34 (bug fix). In particular, AR runs now.
Also explicitly specifies arguments to get_runtime_parameters(), in order to fix a bug in Analyzer and any other bugs due to argument re-ordering.
> Issue34 incorrect vote types in ar

- src/election_data_analysis/__init__.py
> Issue43 clearer err messaging

- src/election_data_analysis/database/create_cdf_db/__init__.py
Reverts ElectionDataAnalysis/election_data_analysis#64
> Revert "Issue60: add indexing for analyzer"

- docs/User_Guide.md
- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/special_formats/__init__.py
- src/election_data_analysis/user_interface/__init__.py
Reverts ElectionDataAnalysis/election_data_analysis#59
> Revert "Issue58: add aggregation export files"

- src/election_data_analysis/analyze/__init__.py
The analyzer code does a pairwise comparison with the winner vs all the non-winners to find anomalies. This created some duplicates on the winner's row of data, which ultimately caused the votes at stake to sometimes equal 0. Removing these dupes solved the problem.
> Issue54: zero votes at stake

- src/election_data_analysis/database/__init__.py
Closes #92 
- Initialises variable _err_ in test_connection()
> Error handling correction

- src/election_data_analysis/database/__init__.py
Closes #58 
- There was some merging issue where the database code did not get merged into main. Adds back in.
- Double checked other parts of the previous branch and those were included.
> Issue58: fix top_counts issue

- src/election_data_analysis/database/__init__.py
Closes #74 
- Removes potential SQL injection spots except for 2 areas
- First, in the jurisdiction hierarchy function, to be addressed with #35 
- Second, in the code that supports the data exports through the front end, to be addressed with #110 
- Checked against all paths used in front end
> address potential SQL injection issues

- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
- Add %s in return for bar, scatter
- add filter on election
- filter out RU types that are election/office specific
- Return None in case of bar chart being unable to calculate a score
> Fixes for vv

- src/election_data_analysis/analyze/__init__.py
Closes Issue #102 
- Removed the unused density_score() function from the code
- There was also a commented out line that called the density_score() function. This was also removed
> Issue102 remove unused analyzer code

- tests/test_dataloader.py
Partially finishes #85 
- Wrote tests for FL, PA, GA, SC, IN, AR, MI
- all tests written in test_dataloader.py
- tests themselves still need to be run
> tests for first 7 states

- requirements.txt
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/special_formats/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/mungers/wi_pri/cdf_elements.txt
- src/mungers/wi_pri/format.config
Closes #127 
Closes #132
Allows munging of multi-sheet Excel files. See wi_pri (Wisconsin) for example
Sorts lists of contests returned when no contests are found
Some bug fixes
> Issue127 multi sheet excel

- src/jurisdictions/Arkansas/dictionary.txt
- src/jurisdictions/Georgia/dictionary.txt
- tests/test_dataloader.py
Corrects tests
Updates AR
Updates GA
> Test resolution 3

- .gitignore
- docs/User_Guide.md
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/jurisdictions/Nevada/BallotMeasureContest.txt
- src/jurisdictions/Nevada/Candidate.txt
- src/jurisdictions/Nevada/CandidateContest.txt
- src/jurisdictions/Nevada/Election.txt
- src/jurisdictions/Nevada/Office.txt
- src/jurisdictions/Nevada/Party.txt
- src/jurisdictions/Nevada/ReportingUnit.txt
- src/jurisdictions/Nevada/dictionary.txt
- src/mungers/nv_gen/cdf_elements.txt
- src/mungers/nv_gen/format.config
Closes #162 
Add code to allow optional `count_of_top_lines_to_skip` parameter for flat files (xls, txt, csv)
Add error-handling
Document changes
Make cosmetic improvement to warnings reporting files
(tested with load_all_from_repo.py)
> Nevada dataloader6

- docs/User_Guide.md
> Document list of recognized encodings

- tests/load_all_from_repo.py
> Copy testing data instead of cloning it

- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
Closes #165 
- Filters contests correctly on election
- Other issues I originally had planned to include in this ticket were substantial enough that they will be broken out into additional tickets
> Issue165 display options filter

- src/election_data_analysis/analyze/__init__.py
Closes #190 
- Add chart title for bar chart
- Add axis title for scatter plot
> Issue190 add chart titles

- src/election_data_analysis/analyze/__init__.py
Close #173 
- round vote at stake, margin, and make more human friendly
> Issue173: round numbers in return for charts

- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
Close #146
- Return `None` when no data found or when error
- Plotting code checks first for None before moving forward
> Issue146 handle no data

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
Close #189
- Uses SQL instead of Pandas to access VoteCount tables
- Found another location to return None when error
> Issue189 optimize candidate loading

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/jurisdictions/Colorado/BallotMeasureContest.txt
- src/jurisdictions/Colorado/Candidate.txt
- src/jurisdictions/Colorado/CandidateContest.txt
- src/jurisdictions/Colorado/Election.txt
- src/jurisdictions/Colorado/Office.txt
- src/jurisdictions/Colorado/Party.txt
- src/jurisdictions/Colorado/ReportingUnit.txt
- src/jurisdictions/Colorado/dictionary.txt
- src/mungers/co_gen/cdf_elements.txt
- src/mungers/co_gen/format.config
- src/mungers/co_gen16/cdf_elements.txt
- src/mungers/co_gen16/format.config
- src/mungers/co_ppp/cdf_elements.txt
- src/mungers/co_ppp/format.config
- src/mungers/co_pri/cdf_elements.txt
- src/mungers/co_pri/format.config
Closes #198 
Munges Colorado
Handles non-numeric, non-blank entries in count columns
> Issue198 strings in count column

- src/election_data_analysis/analyze/__init__.py
Close #196 
- Allow negative votes at stake contests to be displayed, update messaging to reflect
- Fix bug in selecting contests to display
- Close connection when returning None due to error or lack of data
> Issue196 signed votes at stake

- src/election_data_analysis/__init__.py
Closes #208 
Adds better error handling to track_results()
> Improve error handling

- src/election_data_analysis/juris_and_munger/__init__.py
- src/jurisdictions/California/Candidate.txt
- src/jurisdictions/California/dictionary.txt
Closes #212 
Fixes  encoding mismatch bug that caused many Latinx names to be omitted because of accented characters
> Issue212 encodings

- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/jurisdictions/Georgia/dictionary.txt
Closes #216 
Closes #218 
(has nothing to do with  213, that's a typo)
Sets encoding to utf_8 when inserting elements into database
Fixes one error in Georgia dictionary.txt
Enforces title case for all candidates
Introduces some SettingWithCopyWarnings, alas.
> Issue213 title case

- src/election_data_analysis/database/__init__.py
Close #207 
- Include contest, party abbreviations with candidate names
- Order by contest, then party, then candidate name
- Unable to order by candidate last name because extracting last name from `BallotName` is extremely complex
> Issue 207: reorder candidates display

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- Include the party, contest with candidate name when using the search feature
- Scatter plots accept the full candidate name (with contest, party) in addition to just the name itself
> More candidate name cleaning

- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
Close #242 , Close #203 
- Display new wording for scatter plot selections (Candidate total, Candidate absentee-mail, etc)
- Filter data correctly
- Fix bug in visualization where names collided
> Issue203 fix CountItemType filtering

- src/election_data_analysis/database/__init__.py
Close #241 
- candidate search filters on contest type
> Issue 241: candidate search filters on contest type

- src/election_data_analysis/database/__init__.py
Close #248 
- Increase pool size to 20, max overflow of 40
> Issue248: increase pool size

- src/election_data_analysis/analyze/__init__.py
Closes #231
Changed wording of some messages on bar charts
> Change messages

- src/election_data_analysis/juris_and_munger/jurisdiction_templates/Election.txt
- src/jurisdictions/Arkansas/Election.txt
- src/jurisdictions/California/Election.txt
- src/jurisdictions/Colorado/Election.txt
- src/jurisdictions/Delaware/Election.txt
- src/jurisdictions/Florida/Election.txt
- src/jurisdictions/Georgia/Election.txt
- src/jurisdictions/Illinois/Election.txt
- src/jurisdictions/Indiana/Election.txt
- src/jurisdictions/Maine/Election.txt
- src/jurisdictions/Michigan/Election.txt
- src/jurisdictions/Nevada/Election.txt
- src/jurisdictions/North-Carolina/Election.txt
- src/jurisdictions/Ohio/Election.txt
- src/jurisdictions/Pennsylvania/Election.txt
- src/jurisdictions/South-Carolina/Election.txt
- src/jurisdictions/Texas/Election.txt
- src/jurisdictions/Virginia/Election.txt
Removes from each Election.txt file the elections for which we have no data (for the VoteVisualizer)
> Remove empty elections

- src/election_data_analysis/__init__.py
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/special_formats/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/jurisdictions/Arizona/BallotMeasureContest.txt
- src/jurisdictions/Arizona/Candidate.txt
- src/jurisdictions/Arizona/CandidateContest.txt
- src/jurisdictions/Arizona/Election.txt
- src/jurisdictions/Arizona/Office.txt
- src/jurisdictions/Arizona/Party.txt
- src/jurisdictions/Arizona/ReportingUnit.txt
- src/jurisdictions/Arizona/dictionary.txt
- src/mungers/az_xml/cdf_elements.txt
- src/mungers/az_xml/format.config
- tests/test_dataloader.py
- Adds xml file type
- Adds jursdiction and munger files for AZ
- Adds tests for AZ 2020 Primary (except Presidential)
- Adds "skipif" lines to GA tests
> Munge AZ xml format!

- src/election_data_analysis/analyze/__init__.py
Close #219, Close #194 
- Show results with 0 data when other reporting units of same type have data
- Order results for bar chart by margin, not z-score
- Average remaining counties above the total displayed (currently 8) into it's own result set for display
> Issue219 update bar visualization

- src/election_data_analysis/database/__init__.py
Close #174 
- pull election options from VoteCount table
> Issue174: display elections with data

- src/election_data_analysis/__init__.py
> Make file archiving the default behavior for load_all

- src/election_data_analysis/database/__init__.py
Close #275 
- reorder jurisdiction display, first by state, then by election
> Issue 275: reorder states display

- src/election_data_analysis/__init__.py
Close #276 
- remove subdivision_type param for scatter
- Needs coordination with the FE because this is a breaking change
> remove subdivision_type param for scatter

- docs/User_Guide.md
- src/election_data_analysis/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/parameter_file_templates/run_time.ini.template
- tests/load_all_from_repo.py
> Move unloaded files to `unloaded` directory

- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
Close #277 
- Allow all party/district-type selections in dropdown
- Take out some dead code
> Issue277 state contests by party

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/special_formats/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/jurisdictions/South-Carolina/dictionary.txt
- src/mungers/sc_pri/cdf_elements.txt
- tests/load_all_from_repo.py
- tests/test_South-Carolina_2020-Primary.py
Closes #298 
- More efficient cleaning of data (much redundancy removed)
- Minor bug fixes
> Issue298 generic clean

- src/election_data_analysis/munge/__init__.py
- tests/load_all_from_repo.py
- tests/test_Iowa_2020-Primary.py
- tests/test_North-Carolina_2020-Primary.py
- bug fix for files with duplicated candidate names
- IA 2020 Primary passes tests
> IA 2020 passes tests (bug fix)

- src/election_data_analysis/database/__init__.py
Close #282 
- query optimization on candidate votecount
> Issue 282: DB optimizations

- src/ini_files_for_results/de2020p.ini
- src/ini_files_for_results/de2020ppp.ini
- tests/test_Delaware_2020-Primary.py
Converted over the existing tests for Delaware 2020p and made it its own file. Imported in files from the G-drive.
> Add delaware20p test

- src/ini_files_for_results/il18g.ini
- tests/test_Illinois_2018-General.py
Created test for Illinois 2018 general, verified on the VV server. Also added results in file.
> Add illinois18g test

- src/election_data_analysis/database/__init__.py
- tests/load_and_test_all.py
Closes #333 
Fixes bug in remove_database() routine
> Issue333 remove database

- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- tests/California/test_California_2016-General.py
- tests/California/test_California_2020-Primary.py
- tests/Washington/test_Washington_2016-General.py
- tests/Washington/test_Washington_2018-General.py
- tests/Washington/test_Washington_2020-Primary.py
- tests/dont_test_analyzer.py
Closes #320 
- Tests for data in VoteCount table, not just record in _datafile table, in data_exists() function
- Corrects typo in some test files
> Issue320 data exists

- src/election_data_analysis/special_formats/__init__.py
- src/ini_files_for_results/Iowa/ia20g.ini
- src/jurisdictions/Iowa/Candidate.txt
- src/jurisdictions/Iowa/Party.txt
- src/jurisdictions/Iowa/dictionary.txt
- src/mungers/ia_xml/cdf_elements.txt
- src/mungers/ia_xml/format.config
- tests/Iowa/test_Iowa_2020-General.py
- Closes 361
-Munges Iowa 2020 General
> Issue361 xml ugly fail

- src/election_data_analysis/special_formats/__init__.py
- src/ini_files_for_results/Iowa/ia20g.ini
- src/jurisdictions/Iowa/Candidate.txt
- src/jurisdictions/Iowa/Party.txt
- src/jurisdictions/Iowa/dictionary.txt
- src/mungers/ia_xml/cdf_elements.txt
- src/mungers/ia_xml/format.config
- tests/Iowa/test_Iowa_2020-General.py
> Iowa 2020-11-04

- docs/User_Guide.md
- src/election_data_analysis/__init__.py
- tests/load_and_test_all.py
> Allow db removal on fail

- docs/User_Guide.md
- src/election_data_analysis/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/special_formats/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/jurisdictions/Colorado/dictionary.txt
- src/mungers/az_xml/format.config
- src/mungers/co_xml/format.config
- src/mungers/ga_xml/format.config
- src/mungers/ia_xml/format.config
- tests/2020_general_templates/donttest_template_2020-General.py
- tests/Pennsylvania/test_Pennsylvania_2020-General.py
- Fix bug in xml munger (Closes #387)
- Correct xml mungers for AZ, CO, IA
- Add test for single county, single vote type count to test template for 2020
> Issue387 xml bug

- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
Close #352 
- add reported as of date for 2020 General for bar chart
- tests not added (yet) due to changing nature of preliminary files for 2020
> Issue352: Add download date

- tests/2020_general_templates/donttest_template_2020-General.py
> add test_ prefix to data_exists test

- src/election_data_analysis/user_interface/__init__.py
> avoid adding dupes to election-jurisdiction list

- src/election_data_analysis/__init__.py
> remove "other" from list of count_types recognized as standard

- src/ini_files_for_results/Michigan/mi20gen_11_06.ini
- src/mungers/mi_gen2020_by_county/cdf_elements.txt
- src/mungers/mi_gen2020_by_county/format.config
- tests/Michigan/test_Michigan_2020-General.py
> Munge MI 2020 Gen

- tests/load_and_test_all.py
> Issue405 pull ini automatically

- src/election_data_analysis/database/__init__.py
Still needs a test added for AK to ensure future changes don't break this.
> fix AK analyzer code

- src/ini_files_for_results/Arizona/az20gen.ini
- src/mungers/az_json/cdf_elements.txt
- src/mungers/az_json/format.config
- tests/Arizona/test_Arizona_2020-General.py
Added tests for Arizona 2020 General.  Was able to load data and test it, and all tests pass.
> Bryan az 11 05

- src/election_data_analysis/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- tests/Arizona/test_Arizona_2020-Primary.py
- Fixes a bug that occurred when aux_data_dir was missing from the .ini file
> Aux data dir issue

- docs/User_Guide.md
- src/ini_files_for_results/Wisconsin/wi20g_president.ini
- src/jurisdictions/Wisconsin/Candidate.txt
- src/jurisdictions/Wisconsin/Party.txt
- src/jurisdictions/Wisconsin/dictionary.txt
- src/mungers/wi_gen20/cdf_elements.txt
- src/mungers/wi_gen20/format.config
- tests/Wisconsin/test_Wisconsin_2020-General.py
- Added a helpful hint to User_Guide.md in regard to % signs included in .ini files, particularly as a web address where results are located. 
- munge WI 2020
> helpful_hint_User_Guide

- docs/User_Guide.md
- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
Close #492 
- Implement export in NIST format.
> Issue492 nist api

- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/mungers/ak_gen.munger
- src/mungers/ak_gen2.munger
- src/mungers/ak_gen20.munger
- src/mungers/ak_gen_fwab.munger
- src/mungers/ak_gen_fwab20.munger
- src/mungers/ak_gen_votetypes20.munger
- src/mungers/ak_pri.munger
- src/mungers/mi_gen18/aux_meta.txt
- src/mungers/mi_gen18/cit/cdf_elements.txt
- src/mungers/mi_gen18/cit/format.config
- src/mungers/mi_gen18/county/cdf_elements.txt
- src/mungers/mi_gen18/county/format.config
- src/mungers/mi_gen18/name/cdf_elements.txt
- src/mungers/mi_gen18/name/format.config
- src/mungers/mi_gen18/off/cdf_elements.txt
- src/mungers/mi_gen18/off/format.config
- src/mungers/nh_xls_by_county_3_cols_skip_3_lines.munger
- src/mungers/nh_xls_by_county_skip_3.munger
- tests/New-Hampshire/test_New-Hampshire_2020-General.py
Fixes various bugs
Fixes AK and NH munger issues for 2020 General
All archived 2020 General states load and test (except PA, due to internal errors in unofficial PA results, expected to be resolved in official results)
> Ak 2020 gen

- src/election_data_analysis/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- check that constants required by each munger are given in the .ini file
- get rid of obsolete row/column mode
> Reorganize

- src/ini_files_for_results/Louisiana/la20g.ini
- Marks Louisiana results as official
> LA results official

- src/parameter_file_templates/template.munger
> revise template.munger

- docs/User_Guide.md
Closes #557 (updates documentation for munge formulas)
> correct documentation for munge formulas

- docs/User_Guide.md
- src/ini_files_for_results/Wisconsin/wi20g.ini
- src/ini_files_for_results/Wisconsin/wi20g_recount_pres.ini
- src/jurisdictions/Wisconsin/Candidate.txt
- src/jurisdictions/Wisconsin/ReportingUnit.txt
- src/jurisdictions/Wisconsin/dictionary.txt
- src/mungers/wi_ignore_pres.munger
- tests/Wisconsin/test_Wisconsin_2020-General.py
Hi Stephanie - I have the presidential recount munger working (wi_recount.munger) and passing tests for the presidential recount.  However, I have been worked on the Wisconsin general election using the new munger scheme with wi_ignore_pres.munger several times for several hours each, and have not been able to get the data loaded.  If you have time to look at the branch and offer suggestions/make changes, or meet briefly so I can screen share, perhaps that would be more useful.  Thanks!
> wisconsin presidential recount munger + general munger

- src/ini_files_for_results/Louisiana/la20g.ini
- src/ini_files_for_results/Louisiana/la20gCD1.ini
- src/ini_files_for_results/Louisiana/la20gCD2.ini
- src/ini_files_for_results/Louisiana/la20gCD3.ini
- src/ini_files_for_results/Louisiana/la20gCD4.ini
- src/ini_files_for_results/Louisiana/la20gCD5.ini
- src/ini_files_for_results/Louisiana/la20gCD6.ini
- src/ini_files_for_results/Louisiana/la20gSenate.ini
- src/jurisdictions/Louisiana/Candidate.txt
- src/jurisdictions/Louisiana/dictionary.txt
- src/mungers/la_gen.munger
- src/mungers/la_gen_vote_type.munger
- tests/Louisiana/test_Louisiana_2020-General_20201222_official.py
Presidential election were munged earlier. This PR includes US Senate and US house results along with presidential elections.
Results files: https://drive.google.com/drive/folders/1vVe1upFNqO7isdN25PgjM8g6CzZ5pJ9-?usp=sharing
> Louisiana 2020 results

- src/ini_files_for_results/Arkansas/ar20g_20210115.ini
- src/jurisdictions/Arkansas/Candidate.txt
- src/jurisdictions/Arkansas/Party.txt
- src/jurisdictions/Arkansas/dictionary.txt
- src/mungers/ar_xml.munger
- tests/Arkansas/test_Arkansas_2020-General_20210115.py
> Munge AR official results

- src/ini_files_for_results/Hawaii/hi20g_official.ini
> munge HI official

- tests/Alabama/test_Alabama_2020-General.py
Correct Alabama test, for real
> correct Alabama 2020 General test

- docs/User_Guide.md
- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/database/create_cdf_db/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/nist_export/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- tests/analyzer/test_analyzer.py
- tests/load_and_test_all.py
> Issue632 rollup on load

- src/election_data_analysis/__init__.py
- src/election_data_analysis/analyze/__init__.py
- src/election_data_analysis/database/__init__.py
- src/election_data_analysis/juris_and_munger/__init__.py
- src/election_data_analysis/munge/__init__.py
- src/election_data_analysis/nist_export/__init__.py
- src/election_data_analysis/preparation/__init__.py
- src/election_data_analysis/user_interface/__init__.py
- src/ini_files_for_results/Alabama/al20g_official.ini
- src/jurisdictions/Alabama/ReportingUnit.txt
- src/jurisdictions/Alabama/dictionary.txt
- Closes #624 
- Closes #634 
- Creates diff-in-diff calculation (after Herron https://www.liebertpub.com/doi/10.1089/elj.2019.0544)
> Issue624 diff in diff

- docs/User_Guide.md
- src/election_data_analysis/munge/__init__.py
- src/ini_files_for_results/Puerto-Rico/pr20g_governor_official.ini
- src/ini_files_for_results/Puerto-Rico/pr20g_representative_official.ini
- src/ini_files_for_results/Puerto-Rico/pr20g_resident_commissioner_official.ini
- src/ini_files_for_results/Puerto-Rico/pr20g_senate_official.ini
- src/jurisdictions/Puerto-Rico/BallotMeasureContest.txt
- src/jurisdictions/Puerto-Rico/Candidate.txt
- src/jurisdictions/Puerto-Rico/CandidateContest.txt
- src/jurisdictions/Puerto-Rico/Election.txt
- src/jurisdictions/Puerto-Rico/Party.txt
- src/jurisdictions/Puerto-Rico/ReportingUnit.txt
- src/jurisdictions/Puerto-Rico/dictionary.txt
- src/mungers/000_template.munger
- src/mungers/pr20g_legislative.munger
- src/mungers/pr20g_municipality.munger
- src/mungers/pr20g_senate.munger
- tests/Puerto-Rico/test_Puerto-Rico_2020-General_Official.py
- Closes #660 
- Munges Puerto Rico 20g official
> fix bug in multi-column lookups

- src/ini_files_for_results/Alabama/al20g_official.ini
- src/ini_files_for_results/Colorado/co20g_official.ini
- src/ini_files_for_results/Florida/fl20g_official.ini
- src/ini_files_for_results/Hawaii/hi20g_official.ini
- src/ini_files_for_results/Minnesota/mn20g_official_.ini
Add "is_preliminary=False" to ini files as appropriate.
> Is preliminary false

- src/mungers/ks_gen_johnson.munger
- src/mungers/ks_gen_johnson_count_from_B.munger
- src/mungers/ks_gen_sedgwick.munger
- src/mungers/ks_gen_wyandotte.munger
- src/mungers/ks_gen_wyandotte_4_line_header.munger
- src/mungers/ks_gen_wyandotte_4_line_header_first_count_col_3.munger
- src/mungers/ks_gen_wyandotte_count_col_3.munger
- src/mungers/mo_gen_xlsx.munger
Official results for all states + DC + Puerto Rico. (still need other 4 territories)
> munger revisions

- src/election_data_analysis/user_interface/__init__.py
- src/jurisdictions/Maine/dictionary.txt
- src/jurisdictions/Montana/dictionary.txt
- src/mungers/me_one_contest_no_uocava.munger
- tests/Maine/test_Maine_2020-General.py
- tests/Montana/test_Montana_2020-General.py
- tests/Vermont/test_Vermont_2020-General.py
Adds "database" to error keys
Corrects some jurisdiction errors
> Issue675 new error key

- src/electiondata/__init__.py
- src/electiondata/analyze/__init__.py
- src/electiondata/database/__init__.py
Calculate total votes for president by vote type and major subdivision
> Pres votes by vote type

- src/electiondata/__init__.py
- src/electiondata/constants/__init__.py
- src/electiondata/database/__init__.py
- src/electiondata/munge/__init__.py
- src/electiondata/userinterface/__init__.py
- src/ini_files_for_results/Kansas/ks_20g_ks_house_official.ini
- src/ini_files_for_results/New-Hampshire/nh20g_CD2_official.ini
- src/jurisdictions/Wyoming/dictionary.txt
- src/mungers/wy_gen.munger
- Resolve warnings on data load. Notes: 
- sqlAlchemy warnings resolved; 
- fragmented DataFrame warning (Kansas) not resolved, as fixes suggested on line don't seem to work
- openpyxl warning about headers and footers (New Hampshire) not resolved because not completely understood
- BallotMeasureSelection removed from db
- database.add_standard_records() function created:
- "ballot measure selection" Party record
- Yes, No as Candidates (and as CandidateSelections, with Party "ballot measure selection")
-
> Issue709 warnings

- src/electiondata/__init__.py
- src/electiondata/munge/__init__.py
- tests/analyzer_tests/test_analyzer.py
- tests/analyzer_tests/test_exports.py
> Issue730 get started

- requirements.txt
- src/electiondata/userinterface/__init__.py
> Issue740 slugify

- src/electiondata/userinterface/__init__.py
> Issue739 windows encoding
